[tool.poetry]
name = "gettext-lokalise"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
packages = [{include = "gettext_lokalise"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
